language: node_js
services: mongodb
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
- '6.6.0'
before_script:
  - npm install
script:
  - node br.js &
  - npm test
deploy:
  on:
    tags: true
    node: '6.6.0'
  api_key:
    secure: XWt9s1FTcGHkRRvH5VLSc/0gkfFfMHKNohK+Bnlp+7XWBh7hOkRkT+Qee7lt2CSfd1oZSlSaAsz9igEkqsXdlFZCHhMNvQnJ53C4fxdfr4oNRjGZGxz2sJMxZpcyFQknGAp08NG3NGIHlvc1iMMyOWQBKCVwvR03SVKd+GREkaE=
  email: michael@8bitfactory.co
  provider: npm
